version: '3.8'
services:
  mongoApp:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE=schooldb
    ports:
      - 27017:27017
    container_name: mongoApp
    restart: on-failure

  mongo-ui:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root